// Copyright 2021 Adam Chalkley
//
// https://github.com/atc0005/check-statuspage
//
// Licensed under the MIT License. See LICENSE file in the project root for
// full license information.

package main

var boxEvalComponentsTestEntries = []evalComponentsTestdataFile{
	{
		name:                       "(OK) Box, by one valid group Id, one valid subcomponent ID, valid complete expected excluded list",
		filenameFlagValue:          "testdata/components/box-components.json",
		groupFlag:                  defaultGroupFlag,
		groupFlagValue:             "vggytbdllrjt",
		componentFlag:              defaultComponentFlag,
		componentFlagValue:         "k9qs0mx2d5cw",
		evalAllComponentsFlagValue: defaultEvalAllFlagValue,
		expectedExcludedComponentIDs: []string{
			"w0l4pg7zrc66",
			"khm68x6zltbt",
			"y529f1dcxz9n",
			"3072bjbcjxm4",
			"l6vzpnn62cgq",
			"k7gppln3r6hg",
			"m9wrjsglbtpy",
			"r2y11ffxk32x",
			"n3x6zbzwjwch",
			"hvnyl7pqrlkg",
			"9xbfsvbwyhpf",
			"19ym99q18036",
			"wtcp7snm0429",
			"cgbm7n2nch3h",
			"vggytbdllrjt",
			"jqkkbz8yvk8b",
			"c65jnfv7j6mj",
			"qvh7zdkvw690",
			"q5lzw0zgflyh",
			"lp2y8210101z",
			"3jx01d80kg17",
			"jnb7q4jmblxq",
			"rt6135cvpwb0",
			"64t3c6hrtd38",
			"xpk984wrc5z4",
			"k3b0ssj5kl3f",
			"xhqv6cg5n7wj",
			"4g0qfr4s03y8",
			"g58jskvcnlh8",
			"dl6g3rgzpbmw",
			"nlfkp8vly8dw",
			"n48wl8ns3z3w",
			"mkmsdsfl4mxf",
			"pfqdnzt9kjrf",
			"k577rblv57vr",
			"vrpncz5njql2",
			"wpls0qhzglm9",
			"ynrt2yqf7rn8",
			"f42mcm1h8lw9",
			"jvy3knlf7n32",
			"rfmqz1x1xnjm",
			"4qn0knsg3vbd",
			"mbtpbpfcg6vg",
			"qnskj3vl17t6",
			"pllt6gr800yy",
			"v62k7fdw21td",
			"nklhlpplbckl",
			"t1bgldgfmgfs",
			"ld9rqywfvblh",
			"98md1v60byfc",
			"63v1bg2phxrr",
		},
		filterErrorExpected:           false,
		filterResultsMismatchExpected: false,
	},
	{
		name:                       "(OK) Box, by one valid group name, one valid subcomponent ID, valid complete expected excluded list",
		filenameFlagValue:          "testdata/components/box-components.json",
		groupFlag:                  defaultGroupFlag,
		groupFlagValue:             "Box Platform / API",
		componentFlag:              defaultComponentFlag,
		componentFlagValue:         "k9qs0mx2d5cw",
		evalAllComponentsFlagValue: defaultEvalAllFlagValue,
		expectedExcludedComponentIDs: []string{
			"w0l4pg7zrc66",
			"khm68x6zltbt",
			"y529f1dcxz9n",
			"3072bjbcjxm4",
			"l6vzpnn62cgq",
			"k7gppln3r6hg",
			"m9wrjsglbtpy",
			"r2y11ffxk32x",
			"n3x6zbzwjwch",
			"hvnyl7pqrlkg",
			"9xbfsvbwyhpf",
			"19ym99q18036",
			"wtcp7snm0429",
			"cgbm7n2nch3h",
			"vggytbdllrjt",
			"jqkkbz8yvk8b",
			"c65jnfv7j6mj",
			"qvh7zdkvw690",
			"q5lzw0zgflyh",
			"lp2y8210101z",
			"3jx01d80kg17",
			"jnb7q4jmblxq",
			"rt6135cvpwb0",
			"64t3c6hrtd38",
			"xpk984wrc5z4",
			"k3b0ssj5kl3f",
			"xhqv6cg5n7wj",
			"4g0qfr4s03y8",
			"g58jskvcnlh8",
			"dl6g3rgzpbmw",
			"nlfkp8vly8dw",
			"n48wl8ns3z3w",
			"mkmsdsfl4mxf",
			"pfqdnzt9kjrf",
			"k577rblv57vr",
			"vrpncz5njql2",
			"wpls0qhzglm9",
			"ynrt2yqf7rn8",
			"f42mcm1h8lw9",
			"jvy3knlf7n32",
			"rfmqz1x1xnjm",
			"4qn0knsg3vbd",
			"mbtpbpfcg6vg",
			"qnskj3vl17t6",
			"pllt6gr800yy",
			"v62k7fdw21td",
			"nklhlpplbckl",
			"t1bgldgfmgfs",
			"ld9rqywfvblh",
			"98md1v60byfc",
			"63v1bg2phxrr",
		},
		filterErrorExpected:           false,
		filterResultsMismatchExpected: false,
	},
	{
		name:                       "(OK) Box, by one valid group ID, two valid subcomponent IDs, valid complete expected excluded list",
		filenameFlagValue:          "testdata/components/box-components.json",
		groupFlag:                  defaultGroupFlag,
		groupFlagValue:             "vggytbdllrjt",
		componentFlag:              defaultComponentFlag,
		componentFlagValue:         "k9qs0mx2d5cw,rfmqz1x1xnjm",
		evalAllComponentsFlagValue: defaultEvalAllFlagValue,
		expectedExcludedComponentIDs: []string{
			"w0l4pg7zrc66",
			"khm68x6zltbt",
			"y529f1dcxz9n",
			"3072bjbcjxm4",
			"l6vzpnn62cgq",
			"k7gppln3r6hg",
			"m9wrjsglbtpy",
			"r2y11ffxk32x",
			"n3x6zbzwjwch",
			"hvnyl7pqrlkg",
			"9xbfsvbwyhpf",
			"19ym99q18036",
			"wtcp7snm0429",
			"cgbm7n2nch3h",
			"vggytbdllrjt",
			"jqkkbz8yvk8b",
			"c65jnfv7j6mj",
			"qvh7zdkvw690",
			"q5lzw0zgflyh",
			"lp2y8210101z",
			"3jx01d80kg17",
			"jnb7q4jmblxq",
			"rt6135cvpwb0",
			"64t3c6hrtd38",
			"xpk984wrc5z4",
			"k3b0ssj5kl3f",
			"xhqv6cg5n7wj",
			"4g0qfr4s03y8",
			"g58jskvcnlh8",
			"dl6g3rgzpbmw",
			"nlfkp8vly8dw",
			"n48wl8ns3z3w",
			"mkmsdsfl4mxf",
			"pfqdnzt9kjrf",
			"k577rblv57vr",
			"vrpncz5njql2",
			"wpls0qhzglm9",
			"ynrt2yqf7rn8",
			"f42mcm1h8lw9",
			"jvy3knlf7n32",
			"4qn0knsg3vbd",
			"mbtpbpfcg6vg",
			"qnskj3vl17t6",
			"pllt6gr800yy",
			"v62k7fdw21td",
			"nklhlpplbckl",
			"t1bgldgfmgfs",
			"ld9rqywfvblh",
			"98md1v60byfc",
			"63v1bg2phxrr",
		},
		filterErrorExpected:           false,
		filterResultsMismatchExpected: false,
	},
	{
		name:                       "(OK) Box, by one  valid group ID, two valid subcomponent names, valid complete expected excluded list",
		filenameFlagValue:          "testdata/components/box-components.json",
		groupFlag:                  defaultGroupFlag,
		groupFlagValue:             "vggytbdllrjt",
		componentFlag:              defaultComponentFlag,
		componentFlagValue:         "Content API,Box Sign",
		evalAllComponentsFlagValue: defaultEvalAllFlagValue,
		expectedExcludedComponentIDs: []string{
			"w0l4pg7zrc66",
			"khm68x6zltbt",
			"y529f1dcxz9n",
			"3072bjbcjxm4",
			"l6vzpnn62cgq",
			"k7gppln3r6hg",
			"m9wrjsglbtpy",
			"r2y11ffxk32x",
			"n3x6zbzwjwch",
			"hvnyl7pqrlkg",
			"9xbfsvbwyhpf",
			"19ym99q18036",
			"wtcp7snm0429",
			"cgbm7n2nch3h",
			"vggytbdllrjt",
			"jqkkbz8yvk8b",
			"c65jnfv7j6mj",
			"qvh7zdkvw690",
			"q5lzw0zgflyh",
			"lp2y8210101z",
			"3jx01d80kg17",
			"jnb7q4jmblxq",
			"rt6135cvpwb0",
			"64t3c6hrtd38",
			"xpk984wrc5z4",
			"k3b0ssj5kl3f",
			"xhqv6cg5n7wj",
			"4g0qfr4s03y8",
			"g58jskvcnlh8",
			"dl6g3rgzpbmw",
			"nlfkp8vly8dw",
			"n48wl8ns3z3w",
			"mkmsdsfl4mxf",
			"pfqdnzt9kjrf",
			"k577rblv57vr",
			"vrpncz5njql2",
			"wpls0qhzglm9",
			"ynrt2yqf7rn8",
			"f42mcm1h8lw9",
			"jvy3knlf7n32",
			"4qn0knsg3vbd",
			"mbtpbpfcg6vg",
			"qnskj3vl17t6",
			"pllt6gr800yy",
			"v62k7fdw21td",
			"nklhlpplbckl",
			"t1bgldgfmgfs",
			"ld9rqywfvblh",
			"98md1v60byfc",
			"63v1bg2phxrr",
		},
		filterErrorExpected:           false,
		filterResultsMismatchExpected: false,
	},
	{
		name:                          "(FAIL) Box, by one valid group ID, two valid subcomponent IDs, invalid empty expected excluded list",
		filenameFlagValue:             "testdata/components/box-components.json",
		groupFlag:                     defaultGroupFlag,
		groupFlagValue:                "vggytbdllrjt",
		componentFlag:                 defaultComponentFlag,
		componentFlagValue:            "k9qs0mx2d5cw,rfmqz1x1xnjm",
		evalAllComponentsFlagValue:    defaultEvalAllFlagValue,
		expectedExcludedComponentIDs:  []string{},
		filterErrorExpected:           false,
		filterResultsMismatchExpected: true,
	},
	{
		name:                          "(FAIL) Box, by one valid group ID, two valid subcomponent names, invalid empty expected excluded list",
		filenameFlagValue:             "testdata/components/box-components.json",
		groupFlag:                     defaultGroupFlag,
		groupFlagValue:                "vggytbdllrjt",
		componentFlag:                 defaultComponentFlag,
		componentFlagValue:            "Content API,Box Sign",
		evalAllComponentsFlagValue:    defaultEvalAllFlagValue,
		expectedExcludedComponentIDs:  []string{},
		filterErrorExpected:           false,
		filterResultsMismatchExpected: true,
	},
	{
		name:                       "(OK) Box, by one valid group name, three valid subcomponent names, valid complete expected excluded list",
		filenameFlagValue:          "testdata/components/box-components.json",
		groupFlag:                  defaultGroupFlag,
		groupFlagValue:             "Box Platform / API",
		componentFlag:              defaultComponentFlag,
		componentFlagValue:         "Content API,Box Sign,Webhooks",
		evalAllComponentsFlagValue: defaultEvalAllFlagValue,
		expectedExcludedComponentIDs: []string{
			"w0l4pg7zrc66",
			"khm68x6zltbt",
			"y529f1dcxz9n",
			"3072bjbcjxm4",
			"l6vzpnn62cgq",
			"k7gppln3r6hg",
			"m9wrjsglbtpy",
			"r2y11ffxk32x",
			"n3x6zbzwjwch",
			"hvnyl7pqrlkg",
			"9xbfsvbwyhpf",
			"19ym99q18036",
			"wtcp7snm0429",
			"cgbm7n2nch3h",
			"vggytbdllrjt",
			"jqkkbz8yvk8b",
			"c65jnfv7j6mj",
			"qvh7zdkvw690",
			"q5lzw0zgflyh",
			"lp2y8210101z",
			"3jx01d80kg17",
			"jnb7q4jmblxq",
			"rt6135cvpwb0",
			"64t3c6hrtd38",
			"xpk984wrc5z4",
			"k3b0ssj5kl3f",
			"xhqv6cg5n7wj",
			"4g0qfr4s03y8",
			"g58jskvcnlh8",
			"dl6g3rgzpbmw",
			"nlfkp8vly8dw",
			"n48wl8ns3z3w",
			"mkmsdsfl4mxf",
			"pfqdnzt9kjrf",
			"k577rblv57vr",
			"vrpncz5njql2",
			"ynrt2yqf7rn8",
			"f42mcm1h8lw9",
			"jvy3knlf7n32",
			"4qn0knsg3vbd",
			"mbtpbpfcg6vg",
			"qnskj3vl17t6",
			"pllt6gr800yy",
			"v62k7fdw21td",
			"nklhlpplbckl",
			"t1bgldgfmgfs",
			"ld9rqywfvblh",
			"98md1v60byfc",
			"63v1bg2phxrr",
		},
		filterErrorExpected:           false,
		filterResultsMismatchExpected: false,
	},
	{
		name:                       "(FAIL) Box, by one invalid group name, three subcomponent names, valid complete expected excluded list",
		filenameFlagValue:          "testdata/components/box-components.json",
		groupFlag:                  defaultGroupFlag,
		groupFlagValue:             "Box Platform / NotReal",
		componentFlag:              defaultComponentFlag,
		componentFlagValue:         "Content API,Box Sign,Webhooks",
		evalAllComponentsFlagValue: defaultEvalAllFlagValue,
		expectedExcludedComponentIDs: []string{
			"w0l4pg7zrc66",
			"khm68x6zltbt",
			"y529f1dcxz9n",
			"3072bjbcjxm4",
			"l6vzpnn62cgq",
			"k7gppln3r6hg",
			"m9wrjsglbtpy",
			"r2y11ffxk32x",
			"n3x6zbzwjwch",
			"hvnyl7pqrlkg",
			"9xbfsvbwyhpf",
			"19ym99q18036",
			"wtcp7snm0429",
			"cgbm7n2nch3h",
			"vggytbdllrjt",
			"jqkkbz8yvk8b",
			"c65jnfv7j6mj",
			"qvh7zdkvw690",
			"q5lzw0zgflyh",
			"lp2y8210101z",
			"3jx01d80kg17",
			"jnb7q4jmblxq",
			"rt6135cvpwb0",
			"64t3c6hrtd38",
			"xpk984wrc5z4",
			"k3b0ssj5kl3f",
			"xhqv6cg5n7wj",
			"4g0qfr4s03y8",
			"g58jskvcnlh8",
			"dl6g3rgzpbmw",
			"nlfkp8vly8dw",
			"n48wl8ns3z3w",
			"mkmsdsfl4mxf",
			"pfqdnzt9kjrf",
			"k577rblv57vr",
			"vrpncz5njql2",
			"ynrt2yqf7rn8",
			"f42mcm1h8lw9",
			"jvy3knlf7n32",
			"4qn0knsg3vbd",
			"mbtpbpfcg6vg",
			"qnskj3vl17t6",
			"pllt6gr800yy",
			"v62k7fdw21td",
			"nklhlpplbckl",
			"t1bgldgfmgfs",
			"ld9rqywfvblh",
			"98md1v60byfc",
			"63v1bg2phxrr",
		},
		filterErrorExpected:           true,
		filterResultsMismatchExpected: true,
	},
	{
		name:                         "(FAIL) Box, by one invalid group name, three subcomponent names, valid empty expected excluded list",
		filenameFlagValue:            "testdata/components/box-components.json",
		groupFlag:                    defaultGroupFlag,
		groupFlagValue:               "Box Platform / NotReal",
		componentFlag:                defaultComponentFlag,
		componentFlagValue:           "Content API,Box Sign,Webhooks",
		evalAllComponentsFlagValue:   defaultEvalAllFlagValue,
		expectedExcludedComponentIDs: []string{},
		filterErrorExpected:          true,

		// empty list of expected exclusions matches empty list of actual
		// exclusions due to failed filter which we are permitting
		filterResultsMismatchExpected: false,
	},
	{
		name:                          "(OK) Box, eval all components, valid empty expected excluded list",
		filenameFlagValue:             "testdata/components/box-components.json",
		groupFlag:                     "",
		groupFlagValue:                "",
		componentFlag:                 "",
		componentFlagValue:            "",
		evalAllComponentsFlagValue:    "true",
		expectedExcludedComponentIDs:  []string{}, // everything should be matched, so no components will be excluded
		filterErrorExpected:           false,
		filterResultsMismatchExpected: false,
	},
}

// TODO: Fill this in once we have some non-OK component details to work with.
var boxEvalPluginStatusTestEntries = []evalPluginStatusTestdataFile{}
