// Copyright 2021 Adam Chalkley
//
// https://github.com/atc0005/check-statuspage
//
// Licensed under the MIT License. See LICENSE file in the project root for
// full license information.

//nolint:dupl
package main

import "github.com/atc0005/go-nagios"

// Shared var to reduce duplication
var allInstructureComponentIDs = []string{
	"j7jp6sq831c2", "41wg86q5vc14", "9dlvqx1drp3d", "v6m5nhwgtshj",
	"9c01dg04bfg5", "jt1kl5fj472f", "100xy482gkyf", "jw0fn0dnpcgn",
	"57p1tjtk1yq0", "qw5j90r2w7k1", "c8zkn4rlhvw6", "142661pcf7h1",
	"zxq967k6np07", "xwqppk51m3mm", "z5p8qvl1hj1y", "mtytktcmbk6p",
	"ch8dsykb6hln", "qt6q9hfpbljc", "knh34j1129ft", "6pnn3zwfyzxz",
	"d7cxm3fbff4h", "zlyh32dxbwjj", "tlhdyd68vb55", "3q12z77wvfjp",
}

var instructureEvalComponentsTestEntries = []evalComponentsTestdataFile{
	{
		name:                          "(OK) Instructure, eval all, valid empty expected excluded list",
		filenameFlagValue:             "testdata/components/instructure-components.json",
		groupFlag:                     "",
		groupFlagValue:                "",
		componentFlag:                 "",
		componentFlagValue:            "",
		evalAllComponentsFlagValue:    "true",
		expectedExcludedComponentIDs:  []string{},
		filterErrorExpected:           false,
		filterResultsMismatchExpected: false,
	},
	{
		name:                          "(FAIL) Instructure, eval all, invalid complete expected excluded list",
		filenameFlagValue:             "testdata/components/instructure-components.json",
		groupFlag:                     "",
		groupFlagValue:                "",
		componentFlag:                 "",
		componentFlagValue:            "",
		evalAllComponentsFlagValue:    "true",
		expectedExcludedComponentIDs:  allInstructureComponentIDs,
		filterErrorExpected:           false,
		filterResultsMismatchExpected: true, // excluded list should be empty
	},
	{
		name:                       "(OK) Instructure, by group name, valid expected excluded list",
		filenameFlagValue:          "testdata/components/instructure-components.json",
		groupFlag:                  defaultGroupFlag,
		groupFlagValue:             "Canvas",
		componentFlag:              "",
		componentFlagValue:         "",
		evalAllComponentsFlagValue: "false",
		expectedExcludedComponentIDs: []string{
			"j7jp6sq831c2", "41wg86q5vc14", "v6m5nhwgtshj",
			"9c01dg04bfg5", "jt1kl5fj472f", "100xy482gkyf",
			"qw5j90r2w7k1", "c8zkn4rlhvw6", "142661pcf7h1",
			"xwqppk51m3mm",
		},
		filterErrorExpected:           false,
		filterResultsMismatchExpected: false,
	},
	{
		name:                       "(OK) Instructure, by group id, valid expected excluded list",
		filenameFlagValue:          "testdata/components/instructure-components.json",
		groupFlag:                  defaultGroupFlag,
		groupFlagValue:             "41wg86q5vc14", // Canvas
		componentFlag:              "",
		componentFlagValue:         "",
		evalAllComponentsFlagValue: "false",
		expectedExcludedComponentIDs: []string{
			"j7jp6sq831c2", "41wg86q5vc14", "v6m5nhwgtshj",
			"9c01dg04bfg5", "jt1kl5fj472f", "100xy482gkyf",
			"qw5j90r2w7k1", "c8zkn4rlhvw6", "142661pcf7h1",
			"xwqppk51m3mm",
		},
		filterErrorExpected:           false,
		filterResultsMismatchExpected: false,
	},

	{
		name:                       "(OK) Instructure, by group name, component name, valid expected excluded list",
		filenameFlagValue:          "testdata/components/instructure-components.json",
		groupFlag:                  defaultGroupFlag,
		groupFlagValue:             "Canvas",
		componentFlag:              defaultComponentFlag,
		componentFlagValue:         "Canvas",
		evalAllComponentsFlagValue: "false",
		expectedExcludedComponentIDs: []string{
			"j7jp6sq831c2", "41wg86q5vc14", "v6m5nhwgtshj", "9c01dg04bfg5",
			"jt1kl5fj472f", "100xy482gkyf", "jw0fn0dnpcgn", "57p1tjtk1yq0",
			"qw5j90r2w7k1", "c8zkn4rlhvw6", "142661pcf7h1", "zxq967k6np07",
			"xwqppk51m3mm", "z5p8qvl1hj1y", "mtytktcmbk6p", "ch8dsykb6hln",
			"qt6q9hfpbljc", "knh34j1129ft", "6pnn3zwfyzxz", "d7cxm3fbff4h",
			"zlyh32dxbwjj", "tlhdyd68vb55", "3q12z77wvfjp",
		},
		filterErrorExpected:           false,
		filterResultsMismatchExpected: false,
	},
	{
		name:                          "(FAIL) Instructure, by group name, invalid expected excluded list",
		filenameFlagValue:             "testdata/components/instructure-components.json",
		groupFlag:                     defaultGroupFlag,
		groupFlagValue:                "Portfolium",
		componentFlag:                 "",
		componentFlagValue:            "",
		evalAllComponentsFlagValue:    "false",
		expectedExcludedComponentIDs:  allInstructureComponentIDs,
		filterErrorExpected:           false,
		filterResultsMismatchExpected: true, // excluded list should not contain all IDs
	},
	{
		name:                       "(OK) Instructure, by group id, valid expected excluded list",
		filenameFlagValue:          "testdata/components/instructure-components.json",
		groupFlag:                  defaultGroupFlag,
		groupFlagValue:             "9c01dg04bfg5", // Portfolium
		componentFlag:              "",
		componentFlagValue:         "",
		evalAllComponentsFlagValue: "false",
		expectedExcludedComponentIDs: []string{
			"142661pcf7h1", "3q12z77wvfjp", "41wg86q5vc14", "57p1tjtk1yq0",
			"6pnn3zwfyzxz", "9c01dg04bfg5", "9dlvqx1drp3d", "ch8dsykb6hln",
			"d7cxm3fbff4h", "jt1kl5fj472f", "jw0fn0dnpcgn", "knh34j1129ft",
			"mtytktcmbk6p", "qt6q9hfpbljc", "qw5j90r2w7k1", "tlhdyd68vb55",
			"v6m5nhwgtshj", "xwqppk51m3mm", "z5p8qvl1hj1y", "zlyh32dxbwjj",
			"zxq967k6np07",
		},
		filterErrorExpected:           false,
		filterResultsMismatchExpected: false,
	},
	{
		name:                       "(OK) Instructure, by component id, valid expected excluded list",
		filenameFlagValue:          "testdata/components/instructure-components.json",
		groupFlag:                  "",
		groupFlagValue:             "",
		componentFlag:              defaultComponentFlag,
		componentFlagValue:         "v6m5nhwgtshj", // Assessments
		evalAllComponentsFlagValue: "false",
		expectedExcludedComponentIDs: []string{
			"j7jp6sq831c2", "41wg86q5vc14", "9dlvqx1drp3d", "9c01dg04bfg5",
			"jt1kl5fj472f", "100xy482gkyf", "jw0fn0dnpcgn", "57p1tjtk1yq0",
			"qw5j90r2w7k1", "c8zkn4rlhvw6", "142661pcf7h1", "zxq967k6np07",
			"xwqppk51m3mm", "z5p8qvl1hj1y", "mtytktcmbk6p", "ch8dsykb6hln",
			"qt6q9hfpbljc", "knh34j1129ft", "6pnn3zwfyzxz", "d7cxm3fbff4h",
			"zlyh32dxbwjj", "tlhdyd68vb55", "3q12z77wvfjp",
		},
		filterErrorExpected:           false,
		filterResultsMismatchExpected: false,
	},
	{
		name:                       "(OK) Instructure, by component name, valid expected excluded list",
		filenameFlagValue:          "testdata/components/instructure-components.json",
		groupFlag:                  "",
		groupFlagValue:             "",
		componentFlag:              defaultComponentFlag,
		componentFlagValue:         "Web Application",
		evalAllComponentsFlagValue: "false",
		expectedExcludedComponentIDs: []string{
			"j7jp6sq831c2", "41wg86q5vc14", "9dlvqx1drp3d", "v6m5nhwgtshj",
			"9c01dg04bfg5", "jt1kl5fj472f", "jw0fn0dnpcgn", "57p1tjtk1yq0",
			"qw5j90r2w7k1", "c8zkn4rlhvw6", "142661pcf7h1", "zxq967k6np07",
			"xwqppk51m3mm", "z5p8qvl1hj1y", "mtytktcmbk6p", "ch8dsykb6hln",
			"qt6q9hfpbljc", "knh34j1129ft", "6pnn3zwfyzxz", "d7cxm3fbff4h",
			"zlyh32dxbwjj", "tlhdyd68vb55", "3q12z77wvfjp",
		},
		filterErrorExpected:           false,
		filterResultsMismatchExpected: false,
	},
	{
		name:                       "(OK) Instructure, by group name, valid expected excluded list",
		filenameFlagValue:          "testdata/components/instructure-components.json",
		groupFlag:                  defaultGroupFlag,
		groupFlagValue:             "MasteryConnect",
		componentFlag:              "",
		componentFlagValue:         "",
		evalAllComponentsFlagValue: "false",
		expectedExcludedComponentIDs: []string{
			"j7jp6sq831c2", "41wg86q5vc14", "9dlvqx1drp3d", "9c01dg04bfg5",
			"100xy482gkyf", "jw0fn0dnpcgn", "57p1tjtk1yq0", "qw5j90r2w7k1",
			"c8zkn4rlhvw6", "zxq967k6np07", "z5p8qvl1hj1y", "mtytktcmbk6p",
			"ch8dsykb6hln", "qt6q9hfpbljc", "knh34j1129ft", "6pnn3zwfyzxz",
			"d7cxm3fbff4h", "zlyh32dxbwjj", "tlhdyd68vb55", "3q12z77wvfjp",
		},
		filterErrorExpected:           false,
		filterResultsMismatchExpected: false,
	},
	{
		name:                       "(OK) Instructure, by group name, component id, valid expected excluded list",
		filenameFlagValue:          "testdata/components/instructure-components.json",
		groupFlag:                  defaultGroupFlag,
		groupFlagValue:             "Portfolium",
		componentFlag:              defaultComponentFlag,
		componentFlagValue:         "100xy482gkyf", // Web Application
		evalAllComponentsFlagValue: "false",
		expectedExcludedComponentIDs: []string{
			"j7jp6sq831c2", "41wg86q5vc14", "9dlvqx1drp3d", "v6m5nhwgtshj",
			"9c01dg04bfg5", "jt1kl5fj472f", "jw0fn0dnpcgn", "57p1tjtk1yq0",
			"qw5j90r2w7k1", "c8zkn4rlhvw6", "142661pcf7h1", "zxq967k6np07",
			"xwqppk51m3mm", "z5p8qvl1hj1y", "mtytktcmbk6p", "ch8dsykb6hln",
			"qt6q9hfpbljc", "knh34j1129ft", "6pnn3zwfyzxz", "d7cxm3fbff4h",
			"zlyh32dxbwjj", "tlhdyd68vb55", "3q12z77wvfjp",
		},
		filterErrorExpected:           false,
		filterResultsMismatchExpected: false,
	},
	{
		name:                       "(OK) Instructure, by group name, component name, valid expected excluded list",
		filenameFlagValue:          "testdata/components/instructure-components.json",
		groupFlag:                  defaultGroupFlag,
		groupFlagValue:             "Canvas",
		componentFlag:              defaultComponentFlag,
		componentFlagValue:         "— Support: Webform/email", // note the em dash
		evalAllComponentsFlagValue: "false",
		expectedExcludedComponentIDs: []string{
			"j7jp6sq831c2", "41wg86q5vc14", "9dlvqx1drp3d", "v6m5nhwgtshj",
			"9c01dg04bfg5", "jt1kl5fj472f", "100xy482gkyf", "jw0fn0dnpcgn",
			"57p1tjtk1yq0", "qw5j90r2w7k1", "c8zkn4rlhvw6", "142661pcf7h1",
			"zxq967k6np07", "xwqppk51m3mm", "z5p8qvl1hj1y", "mtytktcmbk6p",
			"ch8dsykb6hln", "qt6q9hfpbljc", "knh34j1129ft", "6pnn3zwfyzxz",
			"d7cxm3fbff4h", "tlhdyd68vb55", "3q12z77wvfjp",
		},
		filterErrorExpected:           false,
		filterResultsMismatchExpected: false,
	},
	{
		name:                       "(OK) Instructure, by group name, component name, valid expected excluded list",
		filenameFlagValue:          "testdata/components/instructure-components.json",
		groupFlag:                  defaultGroupFlag,
		groupFlagValue:             "Canvas",
		componentFlag:              defaultComponentFlag,
		componentFlagValue:         "— Support: Phones/Chat",
		evalAllComponentsFlagValue: "false",
		expectedExcludedComponentIDs: []string{
			"j7jp6sq831c2", "41wg86q5vc14", "9dlvqx1drp3d", "v6m5nhwgtshj",
			"9c01dg04bfg5", "jt1kl5fj472f", "100xy482gkyf", "jw0fn0dnpcgn",
			"57p1tjtk1yq0", "qw5j90r2w7k1", "c8zkn4rlhvw6", "142661pcf7h1",
			"zxq967k6np07", "xwqppk51m3mm", "z5p8qvl1hj1y", "mtytktcmbk6p",
			"ch8dsykb6hln", "qt6q9hfpbljc", "knh34j1129ft", "6pnn3zwfyzxz",
			"zlyh32dxbwjj", "tlhdyd68vb55", "3q12z77wvfjp",
		},
		filterErrorExpected:           false,
		filterResultsMismatchExpected: false,
	},
}

var instructureEvalPluginStatusTestEntries = []evalPluginStatusTestdataFile{
	{
		name:                       "(FAIL) Instructure, eval all, invalid plugin status",
		filenameFlagValue:          "testdata/components/instructure-components.json",
		groupFlag:                  "",
		groupFlagValue:             "",
		componentFlag:              "",
		componentFlagValue:         "",
		evalAllComponentsFlagValue: "true",
		expectedPluginStatus: nagios.ServiceState{
			Label:    nagios.StateOKLabel,
			ExitCode: nagios.StateOKExitCode,
		},
		pluginStatusMismatchExpected: true, // actual status is WARNING, we note OK
	},
	{
		name:                       "(OK) Instructure, eval all, valid plugin status",
		filenameFlagValue:          "testdata/components/instructure-components.json",
		groupFlag:                  "",
		groupFlagValue:             "",
		componentFlag:              "",
		componentFlagValue:         "",
		evalAllComponentsFlagValue: "true",
		expectedPluginStatus: nagios.ServiceState{
			Label:    nagios.StateWARNINGLabel,
			ExitCode: nagios.StateWARNINGExitCode,
		},
		pluginStatusMismatchExpected: false,
	},
	{
		name:                       "(OK) Instructure, by group name, valid plugin status",
		filenameFlagValue:          "testdata/components/instructure-components.json",
		groupFlag:                  defaultGroupFlag,
		groupFlagValue:             "Canvas",
		componentFlag:              "",
		componentFlagValue:         "",
		evalAllComponentsFlagValue: "false",
		expectedPluginStatus: nagios.ServiceState{
			Label:    nagios.StateWARNINGLabel,
			ExitCode: nagios.StateWARNINGExitCode,
		},
		pluginStatusMismatchExpected: false,
	},
	{
		name:                       "(FAIL) Instructure, by group name, invalid plugin status",
		filenameFlagValue:          "testdata/components/instructure-components.json",
		groupFlag:                  defaultGroupFlag,
		groupFlagValue:             "Portfolium",
		componentFlag:              "",
		componentFlagValue:         "",
		evalAllComponentsFlagValue: "false",
		expectedPluginStatus: nagios.ServiceState{
			Label:    nagios.StateOKLabel,
			ExitCode: nagios.StateOKExitCode,
		},
		pluginStatusMismatchExpected: true, // actual status is WARNING
	},
	{
		name:                       "(FAIL) Instructure, by group id, invalid plugin status",
		filenameFlagValue:          "testdata/components/instructure-components.json",
		groupFlag:                  defaultGroupFlag,
		groupFlagValue:             "9c01dg04bfg5",
		componentFlag:              "",
		componentFlagValue:         "",
		evalAllComponentsFlagValue: "false",
		expectedPluginStatus: nagios.ServiceState{
			Label:    nagios.StateWARNINGLabel,
			ExitCode: nagios.StateWARNINGExitCode,
		},
		pluginStatusMismatchExpected: false,
	},
	{
		name:                       "(OK) Instructure, by group name, component name, valid plugin status",
		filenameFlagValue:          "testdata/components/instructure-components.json",
		groupFlag:                  defaultGroupFlag,
		groupFlagValue:             "Canvas",
		componentFlag:              defaultComponentFlag,
		componentFlagValue:         "Canvas",
		evalAllComponentsFlagValue: "false",
		expectedPluginStatus: nagios.ServiceState{
			Label:    nagios.StateWARNINGLabel,
			ExitCode: nagios.StateWARNINGExitCode,
		},
		pluginStatusMismatchExpected: false,
	},
	{
		name:                       "(OK) Instructure, by component id, valid plugin status",
		filenameFlagValue:          "testdata/components/instructure-components.json",
		groupFlag:                  "",
		groupFlagValue:             "",
		componentFlag:              defaultComponentFlag,
		componentFlagValue:         "jt1kl5fj472f",
		evalAllComponentsFlagValue: "false",
		expectedPluginStatus: nagios.ServiceState{
			Label:    nagios.StateWARNINGLabel,
			ExitCode: nagios.StateWARNINGExitCode,
		},
		pluginStatusMismatchExpected: false,
	},
	{
		name:                       "(OK) Instructure, by component name, valid plugin status",
		filenameFlagValue:          "testdata/components/instructure-components.json",
		groupFlag:                  "",
		groupFlagValue:             "",
		componentFlag:              defaultComponentFlag,
		componentFlagValue:         "Benchmarks",
		evalAllComponentsFlagValue: "false",
		expectedPluginStatus: nagios.ServiceState{
			Label:    nagios.StateWARNINGLabel,
			ExitCode: nagios.StateWARNINGExitCode,
		},
		pluginStatusMismatchExpected: false,
	},
	{
		name:                       "(OK) Instructure, by group name, valid plugin status",
		filenameFlagValue:          "testdata/components/instructure-components.json",
		groupFlag:                  defaultGroupFlag,
		groupFlagValue:             "Canvas",
		componentFlag:              "",
		componentFlagValue:         "",
		evalAllComponentsFlagValue: "false",
		expectedPluginStatus: nagios.ServiceState{
			Label:    nagios.StateWARNINGLabel,
			ExitCode: nagios.StateWARNINGExitCode,
		},
		pluginStatusMismatchExpected: false,
	},
	{
		name:                       "(OK) Instructure, by group name, component id, valid plugin status",
		filenameFlagValue:          "testdata/components/instructure-components.json",
		groupFlag:                  defaultGroupFlag,
		groupFlagValue:             "MasteryConnect",
		componentFlag:              defaultComponentFlag,
		componentFlagValue:         "v6m5nhwgtshj",
		evalAllComponentsFlagValue: "false",
		expectedPluginStatus: nagios.ServiceState{
			Label:    nagios.StateWARNINGLabel,
			ExitCode: nagios.StateWARNINGExitCode,
		},
		pluginStatusMismatchExpected: false,
	},
	{
		name:                       "(OK) Instructure, by group name, component name, valid plugin status",
		filenameFlagValue:          "testdata/components/instructure-components.json",
		groupFlag:                  defaultGroupFlag,
		groupFlagValue:             "MasteryConnect",
		componentFlag:              defaultComponentFlag,
		componentFlagValue:         "Assessments",
		evalAllComponentsFlagValue: "false",
		expectedPluginStatus: nagios.ServiceState{
			Label:    nagios.StateWARNINGLabel,
			ExitCode: nagios.StateWARNINGExitCode,
		},
		pluginStatusMismatchExpected: false,
	},
	{
		name:                       "(OK) Instructure, by group name, component name, valid plugin status",
		filenameFlagValue:          "testdata/components/instructure-components.json",
		groupFlag:                  defaultGroupFlag,
		groupFlagValue:             "MasteryConnect",
		componentFlag:              defaultComponentFlag,
		componentFlagValue:         "Portal",
		evalAllComponentsFlagValue: "false",
		expectedPluginStatus: nagios.ServiceState{
			Label:    nagios.StateWARNINGLabel,
			ExitCode: nagios.StateWARNINGExitCode,
		},
		pluginStatusMismatchExpected: false,
	},
}
